"""Re-export of :mod:`apply_substitution_for_generated_files` for generated classes.

This lightweight wrapper keeps backwards compatibility with files generated by
:mod:`code_builders` that import ``metamath2py.classes.apply_substitution_for_generated_files``.
"""
from __future__ import annotations

from metamath2py.apply_substitution_for_generated_files import apply_substitution

__all__ = ["apply_substitution"]
